[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "no-cache"

[[headers]]
  for = "/assets/css/*"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate"

[[headers]]
  for = "/assets/js/*"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate"

[[headers]]
  for = "/assets/svg/*"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate"

[[headers]]
  for = "/assets/img/*"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate"

[[headers]]
  for = "/assets/music/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200